### ISSUE TITLE
Load more transactions

### ISSUE THREAD

**Issue by andrewsource147** [KyberNetwork/KyberWallet#105]
@tranvictor Currently, Load more button is not implemented, What is maximum transaction we should display?

![screencapture-localhost-3000-transactions-1507003132924](https://user-images.githubusercontent.com/31321699/31109408-fe433ba4-a829-11e7-8cc8-6193258be626.png)

**Comment by tranvictor** [comment]
We will not support transaction history in new version so I will close this issue
