### ISSUE TITLE
the whole interface doesnt scale to fit the screen

### ISSUE THREAD

**Issue by tranvictor** [KyberNetwork/KyberWallet#15]
![image](https://user-images.githubusercontent.com/5132552/28939337-27f299b6-78bb-11e7-8458-c57ef7c2f723.png)

**Comment by loiluu** [comment]
lets not display them in the same rounds @tranvictor. Lets be consistent on the UI.

**Comment by tranvictor** [comment]
Sure. I think we can use the space to display rate table so users don't have to click on the button to show it. Later on, we might have long list of rates so a separate section for it might be good, think of something like https://poloniex.com/exchange. If we decide to do so, make sure that we only show it with wide enough screens.
