### ISSUE TITLE
 Failed to load resource: the server responded with a status of 405 

### ISSUE THREAD

**Issue by mobilesite** [KyberNetwork/KyberWallet#245]
When I run this project, there is always an error in my Chrome Develop tools: 

> Failed to load resource: the server responded with a status of 405 ()

And the error also shows when browsing https://testnet-wallet.kyber.network/info. It seems that there's some thing wrong when requesting to RPC  for the first time.  Could you please show what's the reason? Thx.

**Comment by andrewsource147** [comment]
same as #93
