### ISSUE TITLE
cannot import keystore

### ISSUE THREAD

**Issue by tranvictor** [KyberNetwork/KyberWallet#25]
Cannot import keystore that is generated by MEW

**Comment by andrewsource** [comment]
In file /src/js/components/Elements/Dropfile.js, can you change line 16 and 17:
`fileReader.onload = () => {
      var keystring = fileReader.result
      try {
        console.log("keystring: ", keystring)
        var address = addressFromKey(keystring)
        this.props.dispatch(uploadKey(
          address, keystring))
      } catch (e) {
        this.props.dispatch(throwError(e.message))
      }
    }`

to

`fileReader.onload = (event) => {
      var keystring = event.target.result
      try {
        console.log("keystring: ", keystring)
        var address = addressFromKey(keystring)
        this.props.dispatch(uploadKey(
          address, keystring))
      } catch (e) {
        this.props.dispatch(throwError(e.message))
      }
    }`

**Comment by whyka** [comment]
I can't reproduce this on FF 54 Windows. FF 55 Mac OS X does not happen too.

**Comment by tranvictor** [comment]
@whyka can you try with FF 54 on Ubuntu?

**Comment by whyka** [comment]
@tranvictor I couldn't re-produce on Ubuntu too. Please view screenshot.

![import_no-txt](https://user-images.githubusercontent.com/1247539/29171897-59f1c624-7e08-11e7-831b-40972799880b.PNG)

**Comment by tranvictor** [comment]
Ok, i will ask the one who contacted me for this issue for better insight. If he doesn't have this issue anymore, i will close this.

**Comment by hahahaha5** [comment]
Hi, I downloaded keystore from MEW, but was not able to import it to the wallet. 
![2017-08-11 1](https://user-images.githubusercontent.com/30520555/29180302-eacbe2c8-7de6-11e7-8b44-047586d0818a.png)

**Comment by andrewsource** [comment]
@hahahaha5 I checked keystore from MEW. The "crypto" key is written to "Crypto", so you cannot import.
