### ISSUE TITLE
Payment related features

### ISSUE THREAD

**Issue by tranvictor** [KyberNetwork/KyberWallet#30]

**Comment by whyka** [comment]
@tranvictor Could you describe this feature?

**Comment by tranvictor** [comment]
@whyka do you want to a try?
This issue is intended for in-house team to work on and we have a lot to discuss than we can just put some descriptions here. If you really insist to try, please contact me directly so we can have better discussion.

**Comment by whyka** [comment]
@tranvictor Sure! How can I contact you? Slack or messenger?

**Comment by tranvictor** [comment]
We will not support this feature in this phase (mainnet launch) yet. It will be discussed and decided the roadmap after that.
