### ISSUE TITLE
Failed Transaction and Stuck in Transaction Confirmation Screen

### ISSUE THREAD

**Issue by imweihuang** [KyberNetwork/KyberWallet#306]
Under the Ropsten Test Net environment, one Eth->KNC transaction failed using MetatMask wallet. [Here](https://ropsten.etherscan.io/tx/0x01e9e2a7ed2647fa8785383b55e627978290788cde15de4da53879e58c09cfc1) is the Tx on etherscan.

Also, sometimes, the transaction confirmation popup doesn't go away after approving transaction on MetaMask (Pic 1). If I close the popup by tapping the cross symbol, the screen freeze (Pic 2).

Pic 1
<img width="1659" alt="screen shot 2018-01-08 at 9 44 55 pm" src="https://user-images.githubusercontent.com/24487707/34706259-10c9894c-f4cc-11e7-98ed-b455b10a82ac.png">

Pic 2
<img width="1675" alt="screen shot 2018-01-08 at 9 45 11 pm" src="https://user-images.githubusercontent.com/24487707/34706263-182cccb2-f4cc-11e7-8450-b572a272b95f.png">

**Comment by tranvictor** [comment]
@imweihuang can you check if there is still pending tx waiting for your approval in your metamask? Basically we have to wait for the user to really approve or reject the tx to avoid any further confusion .
Anw, we will not allow users to close the popup if he is really expected to make an action.

**Comment by imweihuang** [comment]
Oh, you are right, I have a pending tx waiting in my metamask. Just had another try and the pop up works out find.

**Comment by tranvictor** [comment]
Yeah @imweihuang, we are preventing users from closing the pop up now, will try to be more verbose in this case.
