### ISSUE TITLE
Two UI Suggestions

### ISSUE THREAD

**Issue by imweihuang** [KyberNetwork/KyberWallet#315]
1. I think it would helpful giving users instructions when they are trying to login using wrong network.  In the screenshot below, there is a good example from another project.

<img width="1676" alt="screen shot 2018-01-09 at 5 37 30 pm" src="https://user-images.githubusercontent.com/24487707/34749353-9c69a32a-f566-11e7-9a2c-398211cd3cea.png">

2. If I put too many decimals and try to do an exchange, the "CONFIRM" button won't take user to anywhere (no metamask popup and no error message). An error message here or when when user typed too many decimals can be helpful.

<img width="1066" alt="screen shot 2018-01-09 at 5 51 16 pm" src="https://user-images.githubusercontent.com/24487707/34749469-3d16652e-f567-11e7-802a-56b331f41e9c.png">

<img width="1057" alt="screen shot 2018-01-09 at 5 51 24 pm" src="https://user-images.githubusercontent.com/24487707/34749472-4054215e-f567-11e7-958e-5066b18564c3.png">

**Comment by huy23121994** [comment]
@imweihuang: Thanks, it was fixed
