### ISSUE TITLE
about testnet website

### ISSUE THREAD

**Issue by Aion0910** [KyberNetwork/KyberWallet#316]
我建議在https://github.com/KyberNetwork/KyberWallet
網站的https://testnet-wallet.kyber.network
更改成https://new-testnet-wallet.kyber.network/
並且在https://blog.kyber.network/
網站做一個說明與介紹，可以讓所有有興趣的使用者公開測試。

**Comment by andrewsource147** [comment]
@Aion0910  Thanks. It will be updated
