### ISSUE TITLE
中文翻译的问题

### ISSUE THREAD

**Issue by mrchenmo** [KyberNetwork/KyberWallet#318]
右上角的"EXIT"中文翻译成了"推出"，语义应该是"退出"。希望采纳。

**Comment by huy23121994** [comment]
@mrchenmo : thanks, we'll fix this

**Comment by imweihuang** [comment]
@mrchenmo 谢谢你！已经收录了！

**Comment by andrewsource147** [comment]
It is fixed, thanks you
