### ISSUE TITLE
登入之后按下重新整理错误

### ISSUE THREAD

**Issue by Aion0910** [KyberNetwork/KyberWallet#319]
登入之后，按下F5重新整理，会出现404 Not Found的错误。

**Comment by imweihuang** [comment]
Translation of above: 
"after logging in, you will get 404 Not Found error if you press F5 to refresh."

**Comment by andrewsource147** [comment]
@tranvictor Please configure in server

**Comment by andrewsource147** [comment]
We have fixed in mainnet
