### ISSUE TITLE
关于Recent trades

### ISSUE THREAD

**Issue by Aion0910** [KyberNetwork/KyberWallet#321]
我希望不只有Network contract address的近期交易，连登入使用者的交易纪录也可以呈现出来，就不用另外到etherscan查询历史交易纪录。

**Comment by imweihuang** [comment]
Translation of above:
"I hope we can see the recent trades of the user in addition to that of the network contract address, so we don't need to go to the Etherscan to check our history transactions."

**Comment by andrewsource147** [comment]
@Aion0910 We dont record transactions of user due to privacy. Only recent trade transactions in Kyber contract is showed.
