### ISSUE TITLE
KyberWallet - Terms of Use

### ISSUE THREAD

**Issue by hahahaha5** [KyberNetwork/KyberWallet#323]
"Kyber testnet wallet provides a platform for experimenting and understanding our exchange and payment services. The current implementation is not secure in any way. Using it may cause loss of funds and could compromise user privacy. The user bears the sole responsibility for any outcome that is using Kyber testnet wallet."

Should be replaced with 

"Kyber testnet wallet provides a platform for experimenting and understanding our exchange and payment services. The current implementation is not secure in any way. Using it may cause loss of funds and could compromise user privacy. The user is accountable and responsible for any outcome for the use of Kyber testnet wallet."

<img width="1123" alt="screen shot 2018-01-10 at 10 17 59 pm" src="https://user-images.githubusercontent.com/30520555/34777082-26a97d24-f654-11e7-8205-7b3bbeb63973.png">

**Comment by huy23121994** [comment]
@hahahaha5 : thanks tn, it was updated
