### ISSUE TITLE
KyberWallet Transfer Advance Option

### ISSUE THREAD

**Issue by hahahaha5** [KyberNetwork/KyberWallet#325]
Just want to point out if there is a max gas price for transfer function, because in the exchange function, there is a max gas price of 50 gwei

<img width="1109" alt="screen shot 2018-01-10 at 10 25 34 pm" src="https://user-images.githubusercontent.com/30520555/34777417-3f3f1622-f655-11e7-994a-fa28a83c16ed.png">

**Comment by huy23121994** [comment]
@hahahaha5: Thanks, it was updated
