### ISSUE TITLE
KyberWallet Transaction Broadcast

### ISSUE THREAD

**Issue by hahahaha5** [KyberNetwork/KyberWallet#326]
I think it might be better to replace

"Broadcasted transaction to the blockchain" 

with 

"Transaction added to the blockchain"
<img width="1181" alt="screen shot 2018-01-10 at 10 28 44 pm" src="https://user-images.githubusercontent.com/30520555/34777588-bb66673c-f655-11e7-8c85-a8dc788a5a6d.png">

**Comment by huy23121994** [comment]
@hahahaha5: :+1:  It was updated! Thanks
