### ISSUE TITLE
KyberWallet Language Switch

### ISSUE THREAD

**Issue by hahahaha5** [KyberNetwork/KyberWallet#327]
I realize that it is not possible to switch language after opening a wallet. For example, if I access my wallet using my keystore in English, I can't switch to Chinese or Korean after the wallet is unlocked. Thought it would be convenient if the platform allows this function.

**Comment by andrewsource147** [comment]
In current design, it is not easy to add language and info in  header in exchange/transfer screen. We will consider this utility in mainnet.

**Comment by tranvictor** [comment]
@hahahaha5 i think there is no real use case for that. A user will have only one preferred language and he will likely to use it once. Plus that when the address is loaded, there will be other things in that place which are more important. We also discussed with Loi about this.

I will close this issue and might open it back if there are more requests on it. Thanks.

**Comment by hahahaha5** [comment]
All good. No problem at all. Thanks
