### ISSUE TITLE
KyberWallet Chinese Exchange Advance Option 

### ISSUE THREAD

**Issue by hahahaha5** [KyberNetwork/KyberWallet#328]
Replace the advance option "提前“ with "高级选项“

<img width="1085" alt="screen shot 2018-01-10 at 10 35 45 pm" src="https://user-images.githubusercontent.com/30520555/34778151-5e1cfb66-f657-11e7-81e6-883911e1c4b8.png">

**Comment by imweihuang** [comment]
@hahahaha5 已收录，谢谢！

**Comment by huy23121994** [comment]
@hahahaha5: :+1:  It was updated
