### ISSUE TITLE
KyberWallet Exchange and Transfer Broadcast (Chinese)

### ISSUE THREAD

**Issue by hahahaha5** [KyberNetwork/KyberWallet#329]
In the broadcast page, after entering password to approve a transaction, and transaction broadcasted to the blockchain, replace the message

"广播" (or Broadcast in english)

with 

"交易上链“
<img width="1320" alt="screen shot 2018-01-10 at 10 43 10 pm" src="https://user-images.githubusercontent.com/30520555/34778587-aea00d70-f658-11e7-8d8f-284a44a22285.png">

**Comment by imweihuang** [comment]
@hahahaha5 谢谢你的建议，已收录！

**Comment by huy23121994** [comment]
@hahahaha5: It was updated, thanks Tn
