### ISSUE TITLE
关于Advance

### ISSUE THREAD

**Issue by Aion0910** [KyberNetwork/KyberWallet#333]
Best Rate全部清除，输入0.x的x不能是0的问题。

**Comment by Aion0910** [comment]
例如：KNC兑换ETH会发生上述问题。

**Comment by imweihuang** [comment]
@Aion0910 非常感谢！

**Comment by imweihuang** [comment]
Summary: 

In the "Advance" option, user can not have number 0.0... for Best Rate. It automatically clears the field back to 0 if you try to do it.

<img width="832" alt="screen shot 2018-01-11 at 6 47 23 pm" src="https://user-images.githubusercontent.com/24487707/34854594-27a5e08a-f700-11e7-9dd3-5c3591913d0c.png">

**Comment by andrewsource147** [comment]
Fixed in #322 , Thanks you
