### ISSUE TITLE
Detect Ledger / Trezor disconnected 

### ISSUE THREAD

**Issue by amitkot** [KyberNetwork/KyberWallet#358]
Currently when entering the website and selecting Ledger / TREZOR for address import, an error is being displayed if the device is not connected:

<img width="511" alt="screen shot 2018-01-24 at 21 40 56" src="https://user-images.githubusercontent.com/654041/35353295-6c1cef02-014f-11e8-98a0-0caebf8ba5e6.png">

**Comment by andrewsource147** [comment]
thanks, Fixed in #369
