### ISSUE TITLE
Suggest user changes Ledger configuration

### ISSUE THREAD

**Issue by amitkot** [KyberNetwork/KyberWallet#359]
When connecting a Ledger for importing address, the Ledger needs to be configured to allow website access: Ethereum app > Settings > Browser support > Yes. 

I happened to know it, but we should probably suggest the fix to the users (maybe there is a different error code for this situation that we get?), or at least point them to the Ledger documentation (found this for MEW - https://support.ledgerwallet.com/hc/en-us/articles/115005200009).

**Comment by andrewsource147** [comment]
Thanks, Fixed in #375
