### ISSUE TITLE
"Down" arrow on bottom right side of the current token balance list does nothing

### ISSUE THREAD

**Issue by amitkot** [KyberNetwork/KyberWallet#361]
I assume it will be more useful in the future, when we support more currencies. For now, clicking it only changes the height of the balance bar, adding no content.

<img width="1061" alt="screen shot 2018-01-24 at 21 33 31" src="https://user-images.githubusercontent.com/654041/35354691-85096fbe-0153-11e8-9899-990c33bb4f1d.png">

**Comment by tranvictor** [comment]
This is true. @andrewsource please hide it when we have fewer than 8 supported tokens.

**Comment by andrewsource147** [comment]
Fix in master_internal_mainnet
