### ISSUE TITLE
Cannot perform exchange transaction using Ledger

### ISSUE THREAD

**Issue by amitkot** [KyberNetwork/KyberWallet#362]
I selected the To and From coins, entered the sum, clicked the Exchange button, but I keep getting this message screen:

<img width="516" alt="screen shot 2018-01-24 at 22 30 34" src="https://user-images.githubusercontent.com/654041/35355599-7a2b01f4-0156-11e8-9a07-8d604bb8da5a.png">

The Ledger does not display anything, and clicking the "Confirm" button makes the test blink but return again immediately.

If I quit the Ethereum app on the Ledger, after clicking the Confirm button the message changes to:

<img width="515" alt="screen shot 2018-01-24 at 22 40 28" src="https://user-images.githubusercontent.com/654041/35355937-9f489180-0157-11e8-8a05-a4a33939880f.png">

But there is no way to actually confirm it.

**Comment by andrewsource147** [comment]
Thanks, Fixed in #369
