### ISSUE TITLE
DGD price not showing

### ISSUE THREAD

**Issue by hahahaha5** [KyberNetwork/KyberWallet#367]
DGD exchange rate is not showing on Testnet. 

![photo_2018-01-25_09-54-29](https://user-images.githubusercontent.com/30520555/35379255-c60318aa-01b5-11e8-890a-bfb53b824fb9.jpg)

**Comment by tranvictor** [comment]
oh DGD is not listed anymore. Correct behavior is that rate DGD/ETH at the bottom should 0. Thanks.
