### ISSUE TITLE
LocalStorage cause different browsers have different data

### ISSUE THREAD

**Issue by andrewsource** [KyberNetwork/KyberWallet#37]
Currently, all data are stored in localStorage of browsers. Therefore, if I open FF/ Chrome, I'll have different data. In addition, user often clear cache, localStorage, this cause data loss. How about idea store data in local files?

**Comment by tranvictor** [comment]
In our development roadmap, we will not store any keystore nor transaction history so there is no data to be inconsistent. I will  close this issue.
