### ISSUE TITLE
refresh of exchange page returns a 404 Not Found error

### ISSUE THREAD

**Issue by Goldman666** [KyberNetwork/KyberWallet#371]
we can't refresh https://new-testnet-wallet.kyber.network/exchange .. many will try to refresh that page to make sure their transaction succeeded.

**Comment by tranvictor** [comment]
Hi @Goldman666, please test our official testnet version on https://ropsten.kyber.network. This issue is fixed there.

I will close this PR, please open it if you think it is still needed.
