### ISSUE TITLE
Select Entire Balance issue

### ISSUE THREAD

**Issue by Goldman666** [KyberNetwork/KyberWallet#372]
i select entire balance.. and yet it doesnt allow me to buy the entire balance wich is 3.896566 , seems it substract 0.1 eth while fees are just 0.01 
![errorfees](https://user-images.githubusercontent.com/35810644/35404112-1bce15fe-0202-11e8-903b-75a383dedf91.png)

**Comment by tranvictor** [comment]
Thanks for reporting this issue. We fixed this in our internal mainnet version.

I will close this issue, please reopen it later if it remains.
