### ISSUE TITLE
Change the color of text

### ISSUE THREAD

**Issue by loiluu** [KyberNetwork/KyberWallet#373]
The word "for" should not be in green.
<img width="395" alt="screen shot 2018-01-26 at 1 18 13 pm" src="https://user-images.githubusercontent.com/5085931/35426117-8f28b57e-029b-11e8-8df9-577f7c29206b.png">

**Comment by tranvictor** [comment]
@andrewsource147 this could be fixed very fast. Please fix it.

**Comment by andrewsource147** [comment]
Fix in master_internal_mainnet
