### ISSUE TITLE
can't access metamask on brave browser

### ISSUE THREAD

**Issue by freedomntruthseeker** [KyberNetwork/KyberWallet#403]
when using https://ropsten.kyber.network, it does not access metamask embedded on brave

**Comment by andrewsource147** [comment]
@huy23121994 Please check Metamask on Brave browser

**Comment by huy23121994** [comment]
@freedomntruthseeker Make sure Metamask extension was installed in your Brave

**Comment by freedomntruthseeker** [comment]
Yes it’s installed by default (I enabled it n hv eth in it). Let me capture
screen to u a few hours later

**Comment by freedomntruthseeker** [comment]
![2018-02-08_02-02-36](https://user-images.githubusercontent.com/36121623/35933060-787f88b0-0c74-11e8-857b-9eae54005bd9.png)
Pls find capscreen. Cant get it linked to metamask

**Comment by huy23121994** [comment]
In this version, we use Ropsten network. You chose Mainnet on your Metamask. Switch Ropsten network to use.
<img width="357" alt="screen shot 2018-02-08 at 11 35 06 am" src="https://user-images.githubusercontent.com/9770074/35955797-54732918-0cc4-11e8-99e2-046f7d2fc380.png">

**Comment by freedomntruthseeker** [comment]
Oh that’s why. Sorry for this dumb issue I created! I’m a newbie in this
community. Problem solved. Thanks a lot!

**Comment by huy23121994** [comment]
You're welcome
