### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by ductm54** [KyberNetwork/KyberWallet#415]
Exchange from REQ to ETH, tx is pending (1)
Clicked to new exchange
Chose ELF to ETH
(1) is done. Click to pending transaction
Exchange from ELF to ETH.
Approve windows appear (tx fee display is 0)
Click approve and confrim tx on ledger. After confirm from ledger wallet display Done of (1) and approve tx is not sent

**Comment by andrewsource147** [comment]
Fixed in release_0.4.0
