### ISSUE TITLE
The container is not big enough

### ISSUE THREAD

**Issue by mrwentaowinter** [KyberNetwork/KyberWallet#43]
![image](https://user-images.githubusercontent.com/24787072/29053363-4707df90-7c22-11e7-81a1-2648eedb252d.png)

**Comment by tranvictor** [comment]
Hi @mrwentaowinter thank you for the report. However, can I ask if you did anything to change the wallet's color or you just see them as in the photo?

**Comment by mrwentaowinter** [comment]
ignore the color,I change the color by chrome plugin

2017-08-08 19:24 GMT+08:00 Victor Tran <notifications@github.com>:

**Comment by whyka** [comment]
@mrwentaowinter 
Did you run on Ubuntu?
I have the same issue on Ubuntu.
This's caused by the same reason as #44, set https for Roboto font solves problem.

**Comment by tranvictor** [comment]
For issues like this, resolution information is really helpful so I hope you guys can provide that.

**Comment by whyka** [comment]
My resolution is 1152x864.
I see you deployed new version and it not happen again on my Ubuntu.

**Comment by tranvictor** [comment]
@andrewsource are you working on this issue? If you are not, let @whyka work on this.

**Comment by whyka** [comment]
@mrwentaowinter Can you try current https://testnet-wallet.kyber.network/ and confirm if the issue happen again?
