### ISSUE TITLE
Global control (+ button) display weird on Mac OS X

### ISSUE THREAD

**Issue by whyka** [KyberNetwork/KyberWallet#44]
On Mac OS X, I used both Chrome and Safari, (+) button or global control not display correctly for online version https://testnet-wallet.kyber.network/. On Windows it's displayed normally.

I tried to run a local version, it's run fine. You can see results in the attached image. 

<img width="1280" alt="kyber_global-control_css" src="https://user-images.githubusercontent.com/1247539/29058315-e2107d64-7c39-11e7-9ad3-4b23222799ec.png">

**Comment by andrewsource** [comment]
Thanks Whyka.
@tranvictor Consider branch fix_layout.
