### ISSUE TITLE
Typo in Chinese Page

### ISSUE THREAD

**Issue by hahahaha5** [KyberNetwork/KyberWallet#442]
Original texts:
Your address is not eligible for exchange at the moment. Come back later!

Remove:
你的地址目前展示无法交易。请稍后再回来！

Replace with: 
你的地址目前暂时无法交易。请稍后再回来！
![photo_2018-02-11_15-22-44](https://user-images.githubusercontent.com/30520555/36070885-701b5438-0f3f-11e8-9520-d54c60f96612.jpg)

**Comment by andrewsource147** [comment]
@huy23121994 Please check copy
