### ISSUE TITLE
wrong error message

### ISSUE THREAD

**Issue by edwardEvans094** [KyberNetwork/KyberWallet#474]
<img width="986" alt="screen shot 2018-02-24 at 12 29 02 am" src="https://user-images.githubusercontent.com/18391231/36625714-816456aa-1957-11e8-8315-39684a8fc7b5.png">
after exchange success from eth to token, i reverse, exchange from token to eth when network is slow and it show this error.

**Comment by andrewsource147** [comment]
I update error interval
