### ISSUE TITLE
In ropsten network, the rate and minrate return from the method `getAllRatesFromBlockchain` in baseProvider.js seems always to be 0. 

### ISSUE THREAD

**Issue by mobilesite** [KyberNetwork/KyberWallet#483]
In ropsten network, the rate and minrate return from the method `getAllRatesFromBlockchain` in baseProvider.js seems always to be 0. Maybe something wrong in the methods called `getExpectedRates` in wrapperContract.

**Comment by andrewsource147** [comment]
Sorry, what branch you use? this func have beed removed in master branch

**Comment by mobilesite** [comment]
develop branch

**Comment by andrewsource147** [comment]
Please pull newest source code from develop branch. We've not used this api
