### ISSUE TITLE
Cannot click "exchange all balance" when balance is lower than gas fee

### ISSUE THREAD

**Issue by halink0803** [KyberNetwork/KyberWallet#484]
This is not really a bug but the UX make me confuse because there is no message when I cannot click to exchange all my balance.

Step to reproduce:
- Make your eth balance low (like 0.002)
- Click "advance" choose "gas price" to "fast" (or 20 gwei or higher)
- Click balance to "exchange all your balance"

-> Expected behavior: Message announce about "balance is lower than gas price"

-> Current behavior: nothing happen (like we cannot click on that)

**Comment by andrewsource147** [comment]
Fixed in #hotfix_message
