### ISSUE TITLE
Timeout doesn't appear when rate is loading

### ISSUE THREAD

**Issue by Gamvu** [KyberNetwork/KyberWallet#487]
The issue sometimes happens on Windows 10 System, Google browser. 
![timeout doesn t appear when rate is loading](https://user-images.githubusercontent.com/36144425/36774681-9a2c9d90-1c91-11e8-861e-824e316ec7d9.png)
![timeout doesn t appear when rate is loading 2](https://user-images.githubusercontent.com/36144425/36832364-d2e2c318-1d5d-11e8-9a04-47f63ec0daaa.png)

**Comment by andrewsource147** [comment]
Fixed in release_0.5.0
