### ISSUE TITLE
Transaction fee 

### ISSUE THREAD

**Issue by Gamvu** [KyberNetwork/KyberWallet#489]
- Transaction fee in Trezor wallet is not consistent with the one updated on web app when exchanging (Sometimes happen).
- Configuration: Win10-64bit, Google brower.
- Wallet: MetaMask, Trezor, Ledger.
![photo_2018-03-01_11-48-19](https://user-images.githubusercontent.com/36144425/36827519-b46d192c-1d46-11e8-9961-12a20b470e6e.jpg)

**Comment by andrewsource147** [comment]
Fixed in device_manage
