### ISSUE TITLE
App is hung over

### ISSUE THREAD

**Issue by Gamvu** [KyberNetwork/KyberWallet#490]
- App is hung over; some buttons don't work (Exist, Exchange); rate keeps loading; Unable to change coin in both source and target pane.
- Configuration: Win 10 - 64 bit, Google browser. Firefox (happen to MetaMask).
- Happen to MetaMask, Trezor, Json and Ledger.
- Reproducible: Sometimes.

**Comment by andrewsource147** [comment]
Caused by user input "." Fixed in notify_dropdown
