### ISSUE TITLE
Trezor on Firefox

### ISSUE THREAD

**Issue by Gamvu** [KyberNetwork/KyberWallet#491]
![trezor on firefox](https://user-images.githubusercontent.com/36144425/36832259-55cd13ba-1d5d-11e8-8428-593ba2503190.png)
- Trezor keeps loading on Firefox and no timeout.
- Configuration: Win 10- 64 bit, Firefox browser.

**Comment by andrewsource147** [comment]
It've showed popup notify user how to use with trezor
