### ISSUE TITLE
Improvement for Scroll bar

### ISSUE THREAD

**Issue by Gamvu** [KyberNetwork/KyberWallet#495]
- Scroll bar of display error panel should be improved for better display.
- Config: Win 10 - 64 bit, Google and Firefox.
- Wallet: MetaMask.
![improvement for scroll bar](https://user-images.githubusercontent.com/36144425/36895080-2dcc7cd2-1e40-11e8-98e6-03e5de441e62.png)

**Comment by andrewsource147** [comment]
Fixed in device_manage
