### ISSUE TITLE
"Kyber can not handle your amount, please reduce amount" error

### ISSUE THREAD

**Issue by Gamvu** [KyberNetwork/KyberWallet#502]
- The error "Kyber can not handle your amount, please reduce amount" sometimes appear when source amount is 0 or no action is made.
- Config: Win 10 - 64 bit, Google chrome, Firefox.
- Wallet: all.
![issue still happens kyber can t handle your amount](https://user-images.githubusercontent.com/36144425/37013067-791f91c8-212a-11e8-8318-f08ce24b19f3.png)

**Comment by andrewsource147** [comment]
Fixed
