### ISSUE TITLE
Bad feedback copy for users who have not logged in to MetaMask 

### ISSUE THREAD

**Issue by phuongvu11** [KyberNetwork/KyberWallet#510]
Please change this to a more effective dialog- "Please log in to your MetaMask account first" 

<img width="437" alt="screen shot 2018-03-12 at 10 30 54 am" src="https://user-images.githubusercontent.com/19370784/37264584-b5ab20b6-25e0-11e8-9bda-0b2d95816499.png">

**Comment by andrewsource147** [comment]
Fixed in release_0.5.0
