### ISSUE TITLE
A user thinks the default '0' is a little bit confusing.

### ISSUE THREAD

**Issue by imweihuang** [KyberNetwork/KyberWallet#516]
An user thinks the default '0' is a little bit confusing, especially when he is trying to put 0.xx amount, he always thought that is a really '0' so he put '.' right after that.

<img width="339" alt="screen shot 2018-03-19 at 10 42 32 am" src="https://user-images.githubusercontent.com/24487707/37605908-41fa2630-2b62-11e8-93ad-bcdbb9e0f800.png">

**Comment by andrewsource147** [comment]
Thanks you, It have been fixed and we'll deploy soon
