### ISSUE TITLE
Unlocalization and Inconsistency

### ISSUE THREAD

**Issue by Gamvu** [KyberNetwork/KyberWallet#518]
Unlocalization of Click, Rate and Inconsistency of Min rate.
![unloc of rate click and inconsistency of min rate](https://user-images.githubusercontent.com/36144425/37648717-4fb60ee6-2c62-11e8-9a28-52cc3903a6ed.png)
![unloc of click](https://user-images.githubusercontent.com/36144425/37648728-54b878a2-2c62-11e8-8253-c29e4c50473a.png)

**Comment by andrewsource147** [comment]
Fixed
