### ISSUE TITLE
Issue: Your address is not eligible for exchange at the moment. Please come back later!

### ISSUE THREAD

**Issue by tuyenkhuc** [KyberNetwork/KyberWallet#522]
Steps: 
1. Access kyber.network
2. Select Private key exchange
3. Exchange eth-knc (without any input)
4. Super fast to click Exchange button (use Selenium code to click)

Observe:
![1](https://user-images.githubusercontent.com/9961299/37810892-6293941a-2e89-11e8-9f42-21bbcb1bbe93.JPG)

**Comment by andrewsource147** [comment]
Not bug
