### ISSUE TITLE
Issue: missing banner when user access: https://kyber.network//

### ISSUE THREAD

**Issue by tuyenkhuc** [KyberNetwork/KyberWallet#530]
Issue: missing banner when user access  https://kyber.network//  instead of https://kyber.network

Step: 
Access  https://kyber.network//  > Observe
![1_not_ok](https://user-images.githubusercontent.com/9961299/38084228-419ef3b6-3376-11e8-9ebb-27962604735d.PNG)

Expected: 
https://kyber.network// should redirect to https://kyber.network
![1_ok](https://user-images.githubusercontent.com/9961299/38084235-45dbba86-3376-11e8-8e1c-93a655b433e7.PNG)

**Comment by andrewsource147** [comment]
Fixed
