### ISSUE TITLE
Issue Transfer : Your eth balance is not enough for transaction fee in Transfer .

### ISSUE THREAD

**Issue by Gamvu** [KyberNetwork/KyberWallet#531]
Issue:  Input amount (similar balance) > Kyber displays waning noti: Your eth balance is not enough for transaction fee in Transfer > auto hide this noti 
![1_not_ok](https://user-images.githubusercontent.com/36144425/38124624-54566c40-340d-11e8-92e6-16895dc84eb2.PNG)

Expected:
warning noti should displayed as Exchange area.
![1_ok](https://user-images.githubusercontent.com/36144425/38124627-5a17fc48-340d-11e8-8a25-77c6730b3d07.PNG)

**Comment by andrewsource147** [comment]
Fixed in develop
