### ISSUE TITLE
Issue exchange: Can not input dot (.) or 0 number on "To" in Exchange area after select any token.

### ISSUE THREAD

**Issue by tuyenkhuc** [KyberNetwork/KyberWallet#532]
Steps:
Select any token on "To" in exchange area > input dot (.) or 0 number > Obverse
![1_not_ok](https://user-images.githubusercontent.com/9961299/38125106-547c0b5e-3411-11e8-88fe-0aa84ffa8f5d.PNG)

Expected:
Should able to input dot (.) or 0 number as "From"
![1_ok](https://user-images.githubusercontent.com/9961299/38125108-573535a0-3411-11e8-9ce0-ae18e2dd4477.PNG)

**Comment by andrewsource147** [comment]
Fixed
