### ISSUE TITLE
Can't get rate and fetch slippage

### ISSUE THREAD

**Issue by Gamvu** [KyberNetwork/KyberWallet#535]
Can't get rate and fetch slippage when setting min rate and gas price normally.
![screen shot 2018-03-30 at 2 58 51 pm](https://user-images.githubusercontent.com/36144425/38129948-5d35750e-342b-11e8-9177-5db4899a8af6.png)

**Comment by Gamvu** [comment]
Can't fetch slippage when setting min rate or gas price as 0.
![gas price as 0](https://user-images.githubusercontent.com/36144425/38133701-8fb7cafe-343a-11e8-9cfc-30c321530d63.png)
![min rate as 0](https://user-images.githubusercontent.com/36144425/38133708-99eae196-343a-11e8-8c66-cb96b52f46f6.png)

**Comment by andrewsource147** [comment]
Fixed
