### ISSUE TITLE
Gas price

### ISSUE THREAD

**Issue by Gamvu** [KyberNetwork/KyberWallet#537]
1. Actual result: Gas price display badly when the number is too long.
2. Steps to reproduce:
Access kyber.network > make an exchange > Set gas price as the related issue in the SS attached > Click Exchange > Check the SS.
3. Expected result: The issue should be fixed for displaying well.
![gas price displays badly when the number is too long](https://user-images.githubusercontent.com/36144425/38133235-8eb3a95e-3438-11e8-998b-ad41629b24a0.png)

**Comment by andrewsource147** [comment]
Fixed in release_0.6.0
