### ISSUE TITLE
 Metamask issue

### ISSUE THREAD

**Issue by Gamvu** [KyberNetwork/KyberWallet#541]
1. Step to reproduce
- Don't sign in Metamask
- Access https://web3.kyber.network and Get started
- Click Metamask wallet 
2. Actual result:
The notification of error doesn't appear
3. Expected result:
The notification of error should appear like the one in the SS attached.
![screen shot 2018-04-02 at 10 18 02 am](https://user-images.githubusercontent.com/36144425/38181797-2f9e8d8e-365f-11e8-8b10-1ea1a2469fe1.png)

**Comment by andrewsource147** [comment]
Not bug
