### ISSUE TITLE
issue: "no pending transaction" is displayed for the first time open https://kyber.network/exchange

### ISSUE THREAD

**Issue by tuyenkhuc** [KyberNetwork/KyberWallet#542]
Steps:
1. Access kyber.network > exchange > click to notification menu > Exit
2. Access to exchange again.
3. Observe
![1](https://user-images.githubusercontent.com/9961299/38182425-90ee9b66-3663-11e8-99f0-af0c0ee7e3d6.PNG)

Expected:
Should not show that notification when user doesn't click on it.

**Comment by andrewsource147** [comment]
Fixed in release_0.6.0
