### ISSUE TITLE
issue: swap button works wrong.

### ISSUE THREAD

**Issue by tuyenkhuc** [KyberNetwork/KyberWallet#543]
I. Precondition:
Win10, Chrome
II.  Step:
- Access kyber > Exchange > click exchange button >show noti: "số lương chuyển sai định dạng " (or input 0.0 > show noti: "số lượng chuyển quá nhỏ")  > Swap button > Observe: still show this noti.
![1](https://user-images.githubusercontent.com/9961299/38183138-2a0f6ace-3668-11e8-9895-914d2fcacbf0.PNG)

III.Expected:
after click swap button, this noti should not show until user click exchange button.

**Comment by andrewsource147** [comment]
Fixed in release_0.6.0
