### ISSUE TITLE
Grammar issue

### ISSUE THREAD

**Issue by Gamvu** [KyberNetwork/KyberWallet#547]
* Steps to reproduce:
1. Access http://kyber.network
2. Input source amount which is over cap > Check the string in red under source amount box.
* Actual result:
Wrong grammar
* Expected result:
The string should be fixed as the suggested in the SS attached.
![grammar issue](https://user-images.githubusercontent.com/36144425/38227983-18e3810e-372b-11e8-9440-e93462250ff1.png)

**Comment by andrewsource147** [comment]
Fixed in release_0.6.0
