### ISSUE TITLE
Popup of error behaves incorrectly

### ISSUE THREAD

**Issue by Gamvu** [KyberNetwork/KyberWallet#548]
* Steps to reproduce:
1. Access http://kyber.network
2. input extremely high amount into source amount/dest amount > Check the popup in the SS attached
* Actual result:
Popup of error behaves incorrrectly
* Expected result:
The popup should not appear 
![popup of error behaves incorrectly](https://user-images.githubusercontent.com/36144425/38228382-4eae1d4c-372d-11e8-800b-c6ec1f9d8809.png)

**Comment by andrewsource147** [comment]
Fixed in release_0.6.0
