### ISSUE TITLE
Overlapping issue

### ISSUE THREAD

**Issue by Gamvu** [KyberNetwork/KyberWallet#549]
* Steps to reproduce:
1. Access http://kyber.network
2. input amount
3. Click Advanced button
4. Set Gas price as 0000000000000000000000000000 > Move cursor outside > Check the SS attached.
* Actual result:
Overlapping issue
* Expected result:
The issue should be fixed.
![clipping issue](https://user-images.githubusercontent.com/36144425/38229101-3ad70cee-3731-11e8-8a65-3f6d3e53d382.png)

**Comment by tuyenkhuc** [comment]
this issue still happen between width: 713-900

**Comment by andrewsource147** [comment]
Fixed in release_0.6.0
