### ISSUE TITLE
issue: Text is overflowed the input text field on mobile device

### ISSUE THREAD

**Issue by tuyenkhuc** [KyberNetwork/KyberWallet#552]
Precondition:
- Chrome, mobile
Steps:
- Access kyber.network > Click Info button > Observe: Text is overflowed the input text field.

![1](https://user-images.githubusercontent.com/9961299/38347011-bd81997e-38c2-11e8-9d13-17e0500898ca.PNG)

**Comment by andrewsource147** [comment]
Fixed in release_0.6.0
