### ISSUE TITLE
issue: redirect URL not correct when user refresh browser.

### ISSUE THREAD

**Issue by tuyenkhuc** [KyberNetwork/KyberWallet#554]
Steps:
Access kyber network > click to Notification icon > Refresh browser > Observe: redirect URL not correct when user refresh browser.

![1](https://user-images.githubusercontent.com/9961299/38403145-7fa35024-398b-11e8-948e-fc7a3b3edf4a.PNG)
![2](https://user-images.githubusercontent.com/9961299/38403147-7feec57c-398b-11e8-8cf9-89ef7989dbc1.PNG)

Expected:
https://kyber.network/#notifications       should be       https://kyber.network

**Comment by andrewsource147** [comment]
Fixed in release_0.6.0
