### ISSUE TITLE
issue: UI is displayed wrong in Trust and Cipher.

### ISSUE THREAD

**Issue by tuyenkhuc** [KyberNetwork/KyberWallet#556]
issue: UI is displayed wrong in Trust and Cipher.
![screenshot_2018-04-06-12-05-04](https://user-images.githubusercontent.com/9961299/38404422-2ae6d732-3994-11e8-89f6-0d5ac3d649cf.png)

Expected: should displays correctly as Phone browser
![screenshot_2018-04-06-12-05-52](https://user-images.githubusercontent.com/9961299/38404432-3f578d4c-3994-11e8-9e13-6030405dba08.png)

**Comment by andrewsource147** [comment]
Fixed when change header logo
