### ISSUE TITLE
There is no way to modify passphrase/password for a wallet

### ISSUE THREAD

**Issue by hahahaha5** [KyberNetwork/KyberWallet#56]
It'd be great to be able to modify password, but I don't think there's a way to do it yet.

**Comment by tranvictor** [comment]
Yes, it would be helpful if we have this feature. However, for now, people can just download the keystore and use MEW to modify its passphrase.

**Comment by tranvictor** [comment]
In our development roadmap, we will not support this feature so I will close this issue. Please reopen with a strong reason if you still think that we should. Thanks.
