### ISSUE TITLE
issue: Can not get convert amount when user input as format "1.  ",  "2. ", "3. "

### ISSUE THREAD

**Issue by tuyenkhuc** [KyberNetwork/KyberWallet#565]
Steps:
- Access Kyber > Exchange > Input "1." > Issue
![1](https://user-images.githubusercontent.com/9961299/38788926-16e99e7a-4161-11e8-89cf-22e57bfc97bf.PNG)
![1_1](https://user-images.githubusercontent.com/9961299/38788927-17d2354a-4161-11e8-9fbb-9d26825c8850.PNG)

Expected:
- Should get convert amount as normal

**Comment by andrewsource147** [comment]
Fixed in develop
