### ISSUE TITLE
Ask users to download his keystore immediately after a new account is created

### ISSUE THREAD

**Issue by Jonathanzhuye** [KyberNetwork/KyberWallet#57]
I created the wallet, by giving account name and password. When I wanted to access a while later, it asked me to  "import". But to my surprise, the "import" required keystore file and account name. By the time I created the wallet, I wan not aware where is the keystore file. So I cannot access the wallet any more.

**Comment by tranvictor** [comment]
Hi @Jonathanzhuye, you can save (download) your keystore by clicking on the `setting` icon of corresponding account.

To prevent user confusion, we will have a warning message for accounts that users haven't downloaded its keystore. What do you think?

**Comment by Jonathanzhuye** [comment]
Take imtoken, my existing wallet as example. Right after new wallet is created, the APP asked you to back keystore file immediately. And it offers two options to retrieve the file, to save the keystore file directly, and/or write down 12 key words to help to remember the keystore file. I believe these approaches greatly secure the wallet.

Thank you for implementation.

**Comment by andrewsource** [comment]
@tranvictor  My idea is after user create new account, keystore will be downloaded automatically whether she/ he want or not. We can show a dialog, that informs keystore will be downloaded in 5s, 4s,... How do you think about this?

**Comment by tranvictor** [comment]
@andrewsource it is too strict for users, there might be a case that they just want to create a temporary address. I think we should just let the user choose to download it. MyEtherWallet does this very well.
