### ISSUE TITLE
issue: can not load kyber.network when user use Chrome's translate feature.

### ISSUE THREAD

**Issue by tuyenkhuc** [KyberNetwork/KyberWallet#570]
Steps:
Access kyber ( English, Korean, Chinese) > exchange > Right mouse click > Select Chrome's translate > Click at any token > Issue

![1](https://user-images.githubusercontent.com/9961299/39045391-02f7dfe4-44bd-11e8-85c8-5f22b177367f.PNG)

Expected:
Prevent translate from Google Chrome
Reference: https://stackoverflow.com/questions/9628507/how-can-i-tell-google-translate-to-not-translate-a-section-of-a-website

**Comment by andrewsource147** [comment]
Fixed in develop
