### ISSUE TITLE
issue(sometime): Sometime kyber shows notification not correct when user input 0.001 eth on "To" side

### ISSUE THREAD

**Issue by tuyenkhuc** [KyberNetwork/KyberWallet#573]
Steps:
1. Access kyber > exchange > input 0.001 ETH on "To " side > issue:
![1](https://user-images.githubusercontent.com/9961299/39177576-dee0eefa-47d9-11e8-85d4-9407985bf764.PNG)

or
![2](https://user-images.githubusercontent.com/9961299/39177649-0afaa972-47da-11e8-952b-d5ddb6500269.PNG)

Expected:
![3_expected](https://user-images.githubusercontent.com/9961299/39177690-20a78024-47da-11e8-82e8-bf976ffeade5.PNG)

**Comment by andrewsource147** [comment]
Not bug
