### ISSUE TITLE
issue: source amount > balance. However, Kyber does not show noti "Source amount is too high. Your balance is insufficient"

### ISSUE THREAD

**Issue by tuyenkhuc** [KyberNetwork/KyberWallet#574]
Steps:
Access kyber > exchange  > select RCN token (From side) > input 0.001 eth (To side) > issue.

![1](https://user-images.githubusercontent.com/9961299/39177920-b107d510-47da-11e8-82f3-870c45354ae0.PNG)

Expected:
should show noti "Source amount is too high. Your balance is insufficient".

**Comment by andrewsource147** [comment]
Not bug
