### ISSUE TITLE
wallet_issue: Successfully transfered in Wallet, however it was failed in Etherscan.

### ISSUE THREAD

**Issue by tuyenkhuc** [KyberNetwork/KyberWallet#585]
Steps:
access production kyber.network > transfer  DGX to my own address > issue
![1_1](https://user-images.githubusercontent.com/9961299/39615492-ad754d1a-4fa0-11e8-805d-e60c5e515a9b.PNG)
![1_2](https://user-images.githubusercontent.com/9961299/39615494-adbc062e-4fa0-11e8-8096-686554752c98.PNG)
![2_1](https://user-images.githubusercontent.com/9961299/39615495-ae0720d2-4fa0-11e8-9c28-643e6d94ff34.PNG)
![2_2](https://user-images.githubusercontent.com/9961299/39615496-ae403bd8-4fa0-11e8-8d51-fe8110d96063.PNG)
![3_1](https://user-images.githubusercontent.com/9961299/39615497-aed348b0-4fa0-11e8-97cf-26ac62369527.PNG)
![3_2](https://user-images.githubusercontent.com/9961299/39615498-af240c32-4fa0-11e8-8799-46a874b152e4.PNG)

Tx: 
https://etherscan.io/tx/0xec1ab8c4aeacf05fc353271795324d900308d5747451ecf7c11de30ad1a90a65
https://etherscan.io/tx/0x550c925dbbadc41c591835850be23d097faa52f4c9c53a5517507d14cd8efbf9

**Comment by andrewsource147** [comment]
Fixed in fix_transfer_dgx
