### ISSUE TITLE
用户名重复被创建无响应问题

### ISSUE THREAD

**Issue by a56555** [KyberNetwork/KyberWallet#59]
创建钱包页面无反应，更换用户名才可以完成创建，可能因应户名已存在，自己创建用户名重复所导致。

**Comment by tranvictor** [comment]
@a56555 for now, we allow duplicated names so can you double check that the account is created? It might be hard to spot because of the dup names?

**Comment by hahahaha5** [comment]
@a56555 目前我们平台允许不同的钱包有着同一个户名。请您在检查好吗？

**Comment by a56555** [comment]
已检查，没有问题

**Comment by hahahaha5** [comment]
@a56555 好的 谢谢
@tranvictor all good

**Comment by tranvictor** [comment]
Thanks guys, i will close this issue.
