### ISSUE TITLE
网页钱包在1366*768分辨率电脑模态框显示不全

### ISSUE THREAD

**Issue by dengpan1** [KyberNetwork/KyberWallet#60]
![image](https://user-images.githubusercontent.com/15084789/29249481-ef9d061e-8062-11e7-888a-66434ec49d7a.png
 以上是网页截图

**Comment by andrewsource** [comment]
@tranvictor Should we decline height of modal?

**Comment by tranvictor** [comment]
@andrewsource no, the height pretty fit now if advance and crossend is checked. Anw why should we decline it? in order to hide the right scroll bar?

**Comment by andrewsource** [comment]
@tranvictor In screen 1366*768 there additional scroll barin modal. For example, in my screen:

![exchange_modal](https://user-images.githubusercontent.com/20469585/29258412-9ae676ce-80e3-11e7-92e0-73eaf2d389c9.png)

**Comment by tranvictor** [comment]
@andrewsource then lets not cap that container's height. It is enough to have the outer scroll bar.

**Comment by hahahaha5** [comment]
@dengpan1 网页在修正当中
