### ISSUE TITLE
Wallet Send ETH only can input Integer Not Decimal

### ISSUE THREAD

**Issue by stanxii** [KyberNetwork/KyberWallet#62]
When I send eth to others , I must send 1 or 2 or 3 or 4 .... .ETH to other wallet. 

I can't send 3.4 ETH decimal number.

**Comment by tranvictor** [comment]
@stanxii can you tell us which browser (also its version) and the OS you are using?

**Comment by stanxii** [comment]
chrome version  60.0.3112.90（正式版本） （64 位）
Os: win7  64bit

**Comment by tranvictor** [comment]
This should be fixed in referred PR. I will close it, please reopen if it's not fixed for you. Thank you.
