### ISSUE TITLE
Auto input passphrase

### ISSUE THREAD

**Issue by xupf2017** [KyberNetwork/KyberWallet#65]
Auto input passphrase, this is unsafe.

**Comment by tranvictor** [comment]
@xupf2017 can you be more specific why it is unsafe please?

**Comment by stanxii** [comment]
@xupf2017  yes I think same, It is not safe!!!

**Comment by xupf2017** [comment]
Anybody can use my wallet send ether,  without input passphrase, such as my computer is controlled by hacker.

**Comment by xupf2017** [comment]
Just like imtoken, every transaction need passphrase.

**Comment by tranvictor** [comment]
@xupf2017 you are right at some points.

**Comment by andrewsource** [comment]
@xupf2017 If you do not save passphrase when browser ask, it will not be saved in browser. If you save passphrase, anyone use your computer can capture it. It is also normal, when browser ask you to save account /password as you login in any website. In each browser, you can disable "ask to save password", Could you try it?

**Comment by xupf2017** [comment]
Yes, u r right.

**Comment by tranvictor** [comment]
@andrewsource with safari, icloud keychain is used to provide autocompleted password so someone can not just capture remembered password, he needs an icloud password to reveal the whole list. So let's disable that auto complete. It's not a good practice to auto complete crypto passphrase anw.

**Comment by andrewsource** [comment]
@tranvictor There is no standard way to disable auto complete of modern browsers. We can do the trick that insert additional hidden input (type: password, value: constant) in form. This will cause browsers ask to remember this constant password instead of our real password.

**Comment by tranvictor** [comment]
@andrewsource lets find a way to do that. They can make it in other wallets. Your suggestion might work since people will not asked to select remembered password so other inputs are not also overwritten which is a good way to prevent broadcasting errors.

**Comment by tranvictor** [comment]
There is still Safari on mac that can detect passphrase field so I will reopen this issue.

**Comment by tranvictor** [comment]
Safari autocompletion for password input doesn't update other fields hence doesn't affect the form. I will close this issue.
