### ISSUE TITLE
My transaction history is lost after change browser

### ISSUE THREAD

**Issue by xupf2017** [KyberNetwork/KyberWallet#66]
When i changed my browser to chrome, my transaction history is lost,  same jsonfile, only account name is different.

**Comment by tranvictor** [comment]
This is duplicated to #37

**Comment by tranvictor** [comment]
This is one of the limitation of decentralized wallet. We dont keep any of users' data on any centralized storage (servers or cloud) so your transaction history is only available on one browser even if you are using the same address.

In theory, we can fetch all of the transactions of the address from the chain and filter them but that's too complicated for little usage value.

I'm going to close this issue. If you do think that we should support it, please reopen this issue. Thank you.
