### ISSUE TITLE
UI issue when estimating the value between pairs

### ISSUE THREAD

**Issue by ovidiurosu** [KyberNetwork/KyberWallet#67]
In the exchange page enter the following values:

DGD: 1.2341110

the estimate value in ETH will be:
ETH: 0.000000000000

If you change the last digit to:

DGD: 1.2341111

the estimated value in ETH will be:
ETH: 0.673446601147

It seems that if the last digit is 0, the estimated value will be 0.

**Comment by tranvictor** [comment]
@ovidiurosu yes, we are aware of this issue and will fix it in our next version.

**Comment by whyka** [comment]
@tranvictor Please assign this issue and price/amount related issues to me. I'm working on this.

**Comment by tranvictor** [comment]
@whyka sure, please just go ahead.
