### ISSUE TITLE
用谷歌浏览器出现网页崩溃

### ISSUE THREAD

**Issue by e-ason** [KyberNetwork/KyberWallet#70]
用谷歌浏览器出现网页崩溃

**Comment by whyka** [comment]
Duplicate of #63

**Comment by whyka** [comment]
@tranvictor Shouldn't you close duplicated issue?

**Comment by hahahaha5** [comment]
@e-ason 谢谢通知。这是个问题之前有人曾经举报过，团队正在解决。
