### ISSUE TITLE
Could the UI be responsive?

### ISSUE THREAD

**Issue by monokh** [KyberNetwork/KyberWallet#74]
Any chance the UI could be responsive to be usable on different resolutions and mobile phones? 

![image](https://user-images.githubusercontent.com/11529637/29389439-fdbce83c-82e1-11e7-84b3-dd0246232eff.png)

It seems to me there is nothing really stopping this from happening. Issue is mostly in the use of fixed width layout which at least could be modified to collapse through media queries.

**Comment by tranvictor** [comment]
@monokh sure, we are working on responsive layout for the wallet and will be release in next major version update. Thanks.
