### ISSUE TITLE
open transaction link in new window 

### ISSUE THREAD

**Issue by maobisheng** [KyberNetwork/KyberWallet#76]
![kw-01](https://user-images.githubusercontent.com/3703197/29412835-e4dbd3d6-838c-11e7-91eb-5d6293af92ac.png)

suggest to open the transaction link in new window.

**Comment by maobisheng** [comment]
![kw-02](https://user-images.githubusercontent.com/3703197/29413113-da319e56-838d-11e7-8f21-e5c0ad9045d1.png)

this link is also suggest to open it in new window.

**Comment by tranvictor** [comment]
@maobisheng sure, thanks.
