### ISSUE TITLE
CSS issue in create account page

### ISSUE THREAD

**Issue by maobisheng** [KyberNetwork/KyberWallet#77]
![kw-03](https://user-images.githubusercontent.com/3703197/29413320-95979d1c-838e-11e7-9246-ee9c83a70cb0.png)

Refer the screen shot in attachment.

Environment:
Safari, Version 10.1.1 (12603.2.4)

**Comment by maobisheng** [comment]
![image](https://user-images.githubusercontent.com/3703197/29462078-a62c9664-8460-11e7-9c31-d4c1b0dd46f8.png)

It seems the font-size of "Type in your passphrase" is different with "Retype your passphrase".

**Comment by tranvictor** [comment]
@andrewsource please take a look at this.
