### ISSUE TITLE
transaction failed 4 times

### ISSUE THREAD

**Issue by kingavin** [KyberNetwork/KyberWallet#78]
transaction failed 4 times on test network, is it supposed to be failed on a test network??
![kyber wallet 0 0 1](https://user-images.githubusercontent.com/719278/29438625-1262af18-83f7-11e7-8c96-601825572ece.png)

**Comment by tranvictor** [comment]
@kingavin hi, our reserve side is down right now so we are aware of this. This is actually not an issue from the wallet so i will close this issue. I really appreciate your report. Please keep it continues :)
