### ISSUE TITLE
Show input information before users type passphrase

### ISSUE THREAD

**Issue by andrewsource** [KyberNetwork/KyberWallet#81]
- We should show general information user input. After that, they can decide whether to process transaction.
- In the last step, I think we should not allow press enter to process transaction, and not use -> button to confirm transaction (because it is navigate button). We should use button with text like "Confirm"

**Comment by tranvictor** [comment]
Yes, giving a recap of the exchange/send is good.
About the button, right now we have no complains about that and i also don't have problem with that so lets stay simple for this for now.
