### ISSUE TITLE
CSS issue in create account page （previous issue #77）

### ISSUE THREAD

**Issue by maobisheng** [KyberNetwork/KyberWallet#83]
![image](https://user-images.githubusercontent.com/3703197/29462173-07adc610-8461-11e7-9d89-77c7e82457ed.png)

Previous issue https://github.com/KyberNetwork/KyberWallet/issues/77 has been fixed, but it seems the font-size of "Type in your passphrase" is different with "Retype your passphrase".

Environment:
Safari, Version 10.1.1 (12603.2.4)

**Comment by tranvictor** [comment]
@maobisheng thanks, I already reopen the previous issues. Please refer to it #77
