### ISSUE TITLE
suggest open links in new window --- https://testnet-wallet.kyber.network/info

### ISSUE THREAD

**Issue by yuandongsheng0823** [KyberNetwork/KyberWallet#86]
<img width="1042" alt="default" src="https://user-images.githubusercontent.com/31151449/29483780-3c4f30c6-84e2-11e7-8a38-6ded6a4889ba.png">

suggest open these links in new window:
https://testnet-wallet.kyber.network/info

**Comment by tranvictor** [comment]
@yuandongsheng0823 thanks for your suggestion.
