### ISSUE TITLE
css improvement of quick send page

### ISSUE THREAD

**Issue by yangfengming** [KyberNetwork/KyberWallet#87]
![image](https://user-images.githubusercontent.com/14011679/29484188-f7c2b040-84eb-11e7-90b5-b880cad153dd.png)

Back & Next button is not middle aligned with left & right arrow . 

Chrome browser, Version 60.0.3112.101 (Official Build) (64-bit)

**Comment by andrewsource** [comment]
![quick_send](https://user-images.githubusercontent.com/20469585/29484997-6f93584c-84f4-11e7-885c-2f71169ffbbd.png)

My chrome 60.0 display normally. I'm using windows 7. @tranvictor Can you check in OS X?

**Comment by yangfengming** [comment]
Yes, I'm using Mac.

**Comment by tranvictor** [comment]
@andrewsource it is not normal in Safari Mac.
