### ISSUE TITLE
Broadcasting forever without any errors

### ISSUE THREAD

**Issue by yangfengming** [KyberNetwork/KyberWallet#88]
![image](https://user-images.githubusercontent.com/14011679/29484225-bd9732aa-84ec-11e7-81f7-c45291a11e9b.png)

The screen shot is the last step of sending GNOSIS to ETH address.
It should be as below:
[Transaction
xxxxxxxx
is waiting for confirmation...]

**Comment by tranvictor** [comment]
@yangfengming at the time of your screen, the tx is being broadcasted so there is no actual tx yet. The message "transaction ... is waiting..." is only relevant if it is broadcasted to the network.

I'm gonna close this issue, if you have better reason, please edit and reopen this issue. Thanks.

**Comment by yangfengming** [comment]
I wait about half an hour and the tx is still being broadcasted, and I can't find the transaction history in "Transaction" page.
![image](https://user-images.githubusercontent.com/14011679/29484649-a296e406-84f5-11e7-800a-d5a192c03c20.png)

**Comment by tranvictor** [comment]
@yangfengming that might be a bigger problem of a message. Can you reproduce that error and describe here the steps to reproduce it?

**Comment by yangfengming** [comment]
My account overview:
![image](https://user-images.githubusercontent.com/14011679/29491701-06596f54-8596-11e7-857b-607ba26fc121.png)

Click "Exchange & Send" button and choose GNO and fill 0.1 as "Exchange", choose ETH as "Excepted to receive".
![image](https://user-images.githubusercontent.com/14011679/29491706-2e229a42-8596-11e7-84ba-db7f12f54175.png)

Then click Next button goto the next step:
![image](https://user-images.githubusercontent.com/14011679/29491726-c27939c6-8596-11e7-9f86-9b7758abd067.png)

Input passpharse and click Next, the last step as below and without any errors.
![image](https://user-images.githubusercontent.com/14011679/29491726-c27939c6-8596-11e7-9f86-9b7758abd067.png)

**Comment by loiluu** [comment]
Seems like you dont have enough ETH balance to broadcast the tx. This
should be fixed.

Thanks,
Loi Luu.

**Comment by tranvictor** [comment]
I am going to close this issue. It should be fixed in referred PR. Please reopen it if it is still happening for you. Thanks.
