### ISSUE TITLE
Web directories don't open unless called from within the main site

### ISSUE THREAD

**Issue by aenaus** [KyberNetwork/KyberWallet#93]
https://testnet-wallet.kyber.network/transactions  does not work (404) when being called directly as a url, only when  being requested while in the https://testnet-wallet.kyber.network page.
Same for all /dirs under the main page

**Comment by andrewsource147** [comment]
@tranvictor Please check configuration in server, the localhost work well

**Comment by tranvictor** [comment]
Sure i will check later

**Comment by tranvictor** [comment]
We fixed this in our latest ropsten version. I will close this issue. Thanks.
