### ISSUE TITLE
Transactions with 7677468 gas limit are  pending indefinitely

### ISSUE THREAD

**Issue by aenaus** [KyberNetwork/KyberWallet#95]
I am not able to submit a transaction with 7677468 gas limit even though my balance covers gas * gas price

**Comment by tranvictor** [comment]
7.6M is too many to a block gas limit so the wallet is supposed to show an error instead of leaving it pending forever. Will fix it soon.

**Comment by tranvictor** [comment]
I'm going to close this issue because it is supposed to be fixed with the referred PR. If you have time, please test it and might reopen the issue if it still persists. Thank you.
