### ISSUE TITLE
KNC in wallet and Etherscan not matching

### ISSUE THREAD

**Issue by hahahaha5** [KyberNetwork/KyberWallet#98]
My transaction hash: 0x2bb482e129bff83f7f42a6fb35e4af886075b831c35d867ce5648ef0c126b06b

It says that I'm supposed to be getting 6,000 KNC, but wallet only displays 2,600 KNC
![4](https://user-images.githubusercontent.com/30520555/30198325-a84f6e86-949f-11e7-8c08-a0c1712a847a.png)

**Comment by tranvictor** [comment]
Because infuration kovan node is forked to be a different chain to etherscan and mew so the wallet behave this way. It is not that the wallet is malfunctioning so I will close this issue.

**Comment by hahahaha5** [comment]
Okay. Thanks Victor.
