### ISSUE TITLE
Kyber Wallet UX/UI Pop-up window Freeze

### ISSUE THREAD

**Issue by spidey6600** [KyberNetwork/KyberWallet#99]
I recommend freezing the pop-up window instead of letting it disappear while clicking outside as accidental outside clicking might cause people to lose precious time during the uncapped tokensale. You already have a close button on it.

**Comment by tranvictor** [comment]
Thanks @spidey6600, we will take your recommendation into our mainnet wallet version.

**Comment by tranvictor** [comment]
This is no longer relevant to our current version. I will close this issue. Thanks.
